// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATD_jCS34zyZs1DV5WBBxBiALU671AqE',
    appId: '1:623410139948:web:28bc3a79473778b3fc5289',
    messagingSenderId: '623410139948',
    projectId: 'pansys-d431e',
    authDomain: 'pansys-d431e.firebaseapp.com',
    storageBucket: 'pansys-d431e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyj7qmiEh4B71QlcsU3FSVTd66i2C0YZk',
    appId: '1:623410139948:android:4ac6e28914d67e5dfc5289',
    messagingSenderId: '623410139948',
    projectId: 'pansys-d431e',
    storageBucket: 'pansys-d431e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD50MKnzkVrGYdZ0daIYIXWJfC9vsAoAJo',
    appId: '1:623410139948:ios:f4302a804c55d792fc5289',
    messagingSenderId: '623410139948',
    projectId: 'pansys-d431e',
    storageBucket: 'pansys-d431e.firebasestorage.app',
    iosBundleId: 'com.pansys.pansys',
  );
}
